import type { Theme } from "@engrams/user-preferences";

// Dracula Classic and Alucard Classic: https://draculatheme.com/spec
const dracula: Record<Theme, Record<string, string>> = {
  light: {
    "syntax-background": "#fffbeb",
    "syntax-plain": "#1f1f1f",
    "syntax-comment": "#6c664b",
    "syntax-keyword": "#a3144d",
    "syntax-string": "#846e15",
    "syntax-number": "#a34d14",
    "syntax-function": "#14710a",
    "syntax-type": "#036a96",
    "syntax-deleted": "#cb3a2a",
    "git-added": "#14710a",
    "git-deleted": "#cb3a2a",
    "git-modified": "#644ac9",
    "terminal-background": "#fffbeb",
    "terminal-foreground": "#1f1f1f",
    "terminal-cursor": "#1f1f1f",
    "terminal-cursor-accent": "#fffbeb",
    "terminal-selection": "#cfcfde",
    "terminal-selection-foreground": "#1f1f1f",
    "terminal-black": "#fffbeb",
    "terminal-red": "#cb3a2a",
    "terminal-green": "#14710a",
    "terminal-yellow": "#846e15",
    "terminal-blue": "#644ac9",
    "terminal-magenta": "#a3144d",
    "terminal-cyan": "#036a96",
    "terminal-white": "#1f1f1f",
    "terminal-bright-black": "#6c664b",
    "terminal-bright-red": "#d74c3d",
    "terminal-bright-green": "#198d0c",
    "terminal-bright-yellow": "#9e841a",
    "terminal-bright-blue": "#7862d0",
    "terminal-bright-magenta": "#bf185a",
    "terminal-bright-cyan": "#047fb4",
    "terminal-bright-white": "#2c2b31",
  },
  dark: {
    "syntax-background": "#282a36",
    "syntax-plain": "#f8f8f2",
    "syntax-comment": "#6272a4",
    "syntax-keyword": "#ff79c6",
    "syntax-string": "#f1fa8c",
    "syntax-number": "#ffb86c",
    "syntax-function": "#50fa7b",
    "syntax-type": "#8be9fd",
    "syntax-deleted": "#ff5555",
    "git-added": "#50fa7b",
    "git-deleted": "#ff5555",
    "git-modified": "#bd93f9",
    "terminal-background": "#282a36",
    "terminal-foreground": "#f8f8f2",
    "terminal-cursor": "#f8f8f2",
    "terminal-cursor-accent": "#282a36",
    "terminal-selection": "#44475a",
    "terminal-selection-foreground": "#f8f8f2",
    "terminal-black": "#21222c",
    "terminal-red": "#ff5555",
    "terminal-green": "#50fa7b",
    "terminal-yellow": "#f1fa8c",
    "terminal-blue": "#bd93f9",
    "terminal-magenta": "#ff79c6",
    "terminal-cyan": "#8be9fd",
    "terminal-white": "#f8f8f2",
    "terminal-bright-black": "#6272a4",
    "terminal-bright-red": "#ff6e6e",
    "terminal-bright-green": "#69ff94",
    "terminal-bright-yellow": "#ffffa5",
    "terminal-bright-blue": "#d6acff",
    "terminal-bright-magenta": "#ff92df",
    "terminal-bright-cyan": "#a4ffff",
    "terminal-bright-white": "#ffffff",
  },
};

type AnsiPalette = readonly [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
];
interface Palette {
  background: string;
  foreground: string;
  comment: string;
  keyword: string;
  string: string;
  number: string;
  function: string;
  type: string;
  red: string;
  green: string;
  modified: string;
  selection: string;
  selectionForeground: string;
  cursor: string;
  ansi: AnsiPalette;
}
const ansiRoles = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"] as const;
/** Map palette roles to CSS tokens without changing the reference ANSI slots. */
function renderer(palette: Palette): Record<string, string> {
  const tokens: Record<string, string> = {
    "syntax-background": palette.background,
    "syntax-plain": palette.foreground,
    "syntax-comment": palette.comment,
    "syntax-keyword": palette.keyword,
    "syntax-string": palette.string,
    "syntax-number": palette.number,
    "syntax-function": palette.function,
    "syntax-type": palette.type,
    "syntax-deleted": palette.red,
    "git-added": palette.green,
    "git-deleted": palette.red,
    "git-modified": palette.modified,
    "terminal-background": palette.background,
    "terminal-foreground": palette.foreground,
    "terminal-cursor": palette.cursor,
    "terminal-cursor-accent": palette.background,
    "terminal-selection": palette.selection,
    "terminal-selection-foreground": palette.selectionForeground,
  };
  for (const [index, role] of ansiRoles.entries()) {
    tokens[`terminal-${role}`] = palette.ansi[index]!;
    tokens[`terminal-bright-${role}`] = palette.ansi[index + 8]!;
  }
  return tokens;
}

// Catppuccin Latte and Mocha. Syntax roles follow the official style guide.
// https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md
// ANSI and cursor colors: https://github.com/catppuccin/alacritty/blob/main/catppuccin-latte.toml
// https://github.com/catppuccin/alacritty/blob/main/catppuccin-mocha.toml
const catppuccin = {
  light: renderer({
    background: "#eff1f5",
    foreground: "#4c4f69",
    comment: "#8c8fa1",
    keyword: "#8839ef",
    string: "#40a02b",
    number: "#fe640b",
    function: "#1e66f5",
    type: "#df8e1d",
    red: "#d20f39",
    green: "#40a02b",
    modified: "#df8e1d",
    selection: "#dc8a78",
    selectionForeground: "#1e1e2e",
    cursor: "#dc8a78",
    ansi: [
      "#bcc0cc",
      "#d20f39",
      "#40a02b",
      "#df8e1d",
      "#1e66f5",
      "#ea76cb",
      "#179299",
      "#5c5f77",
      "#acb0be",
      "#d20f39",
      "#40a02b",
      "#df8e1d",
      "#1e66f5",
      "#ea76cb",
      "#179299",
      "#6c6f85",
    ],
  }),
  dark: renderer({
    background: "#1e1e2e",
    foreground: "#cdd6f4",
    comment: "#7f849c",
    keyword: "#cba6f7",
    string: "#a6e3a1",
    number: "#fab387",
    function: "#89b4fa",
    type: "#f9e2af",
    red: "#f38ba8",
    green: "#a6e3a1",
    modified: "#f9e2af",
    selection: "#f5e0dc",
    selectionForeground: "#1e1e2e",
    cursor: "#f5e0dc",
    ansi: [
      "#45475a",
      "#f38ba8",
      "#a6e3a1",
      "#f9e2af",
      "#89b4fa",
      "#f5c2e7",
      "#94e2d5",
      "#bac2de",
      "#585b70",
      "#f38ba8",
      "#a6e3a1",
      "#f9e2af",
      "#89b4fa",
      "#f5c2e7",
      "#94e2d5",
      "#a6adc8",
    ],
  }),
};

// Snow Storm and Polar Night use Nord's semantic colors and exact ANSI slots.
// https://www.nordtheme.com/docs/colors-and-palettes/
// https://github.com/nordtheme/xresources/blob/develop/src/nord
const nordAnsi: AnsiPalette = [
  "#3b4252",
  "#bf616a",
  "#a3be8c",
  "#ebcb8b",
  "#81a1c1",
  "#b48ead",
  "#88c0d0",
  "#e5e9f0",
  "#4c566a",
  "#bf616a",
  "#a3be8c",
  "#ebcb8b",
  "#81a1c1",
  "#b48ead",
  "#8fbcbb",
  "#eceff4",
];
const nord = {
  light: renderer({
    background: "#eceff4",
    foreground: "#2e3440",
    comment: "#4c566a",
    keyword: "#81a1c1",
    string: "#a3be8c",
    number: "#b48ead",
    function: "#88c0d0",
    type: "#8fbcbb",
    red: "#bf616a",
    green: "#a3be8c",
    modified: "#81a1c1",
    selection: "#d8dee9",
    selectionForeground: "#2e3440",
    cursor: "#2e3440",
    ansi: nordAnsi,
  }),
  dark: renderer({
    background: "#2e3440",
    foreground: "#d8dee9",
    comment: "#4c566a",
    keyword: "#81a1c1",
    string: "#a3be8c",
    number: "#b48ead",
    function: "#88c0d0",
    type: "#8fbcbb",
    red: "#bf616a",
    green: "#a3be8c",
    modified: "#81a1c1",
    selection: "#434c5e",
    selectionForeground: "#d8dee9",
    cursor: "#d8dee9",
    ansi: nordAnsi,
  }),
};

// Solarized's light mode reverses the base colors, including their ANSI slots.
// https://ethanschoonover.com/solarized/
// https://github.com/altercation/solarized/blob/master/xresources/solarized
const solarized = {
  light: renderer({
    background: "#fdf6e3",
    foreground: "#657b83",
    comment: "#93a1a1",
    keyword: "#859900",
    string: "#2aa198",
    number: "#d33682",
    function: "#268bd2",
    type: "#b58900",
    red: "#dc322f",
    green: "#859900",
    modified: "#b58900",
    selection: "#eee8d5",
    selectionForeground: "#073642",
    cursor: "#586e75",
    ansi: [
      "#eee8d5",
      "#dc322f",
      "#859900",
      "#b58900",
      "#268bd2",
      "#d33682",
      "#2aa198",
      "#073642",
      "#fdf6e3",
      "#cb4b16",
      "#93a1a1",
      "#839496",
      "#657b83",
      "#6c71c4",
      "#586e75",
      "#002b36",
    ],
  }),
  dark: renderer({
    background: "#002b36",
    foreground: "#839496",
    comment: "#586e75",
    keyword: "#859900",
    string: "#2aa198",
    number: "#d33682",
    function: "#268bd2",
    type: "#b58900",
    red: "#dc322f",
    green: "#859900",
    modified: "#b58900",
    selection: "#073642",
    selectionForeground: "#93a1a1",
    cursor: "#93a1a1",
    ansi: [
      "#073642",
      "#dc322f",
      "#859900",
      "#b58900",
      "#268bd2",
      "#d33682",
      "#2aa198",
      "#eee8d5",
      "#002b36",
      "#cb4b16",
      "#586e75",
      "#657b83",
      "#839496",
      "#6c71c4",
      "#93a1a1",
      "#fdf6e3",
    ],
  }),
};

// Gruvbox uses medium-contrast backgrounds and the original Vim terminal slots.
// https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim
const gruvbox = {
  light: renderer({
    background: "#fbf1c7",
    foreground: "#3c3836",
    comment: "#928374",
    keyword: "#9d0006",
    string: "#79740e",
    number: "#8f3f71",
    function: "#79740e",
    type: "#b57614",
    red: "#9d0006",
    green: "#79740e",
    modified: "#b57614",
    selection: "#ebdbb2",
    selectionForeground: "#3c3836",
    cursor: "#3c3836",
    ansi: [
      "#fbf1c7",
      "#cc241d",
      "#98971a",
      "#d79921",
      "#458588",
      "#b16286",
      "#689d6a",
      "#7c6f64",
      "#928374",
      "#9d0006",
      "#79740e",
      "#b57614",
      "#076678",
      "#8f3f71",
      "#427b58",
      "#3c3836",
    ],
  }),
  dark: renderer({
    background: "#282828",
    foreground: "#ebdbb2",
    comment: "#928374",
    keyword: "#fb4934",
    string: "#b8bb26",
    number: "#d3869b",
    function: "#b8bb26",
    type: "#fabd2f",
    red: "#fb4934",
    green: "#b8bb26",
    modified: "#fabd2f",
    selection: "#3c3836",
    selectionForeground: "#ebdbb2",
    cursor: "#ebdbb2",
    ansi: [
      "#282828",
      "#cc241d",
      "#98971a",
      "#d79921",
      "#458588",
      "#b16286",
      "#689d6a",
      "#a89984",
      "#928374",
      "#fb4934",
      "#b8bb26",
      "#fabd2f",
      "#83a598",
      "#d3869b",
      "#8ec07c",
      "#ebdbb2",
    ],
  }),
};
const rendererPresets: Readonly<Record<string, Record<Theme, Record<string, string>>>> = {
  dracula,
  catppuccin,
  nord,
  solarized,
  gruvbox,
};
/** Return the reference renderer palette for a built-in scheme and mode. */
export function getPresetRendererTokens(
  id: string,
  theme: Theme,
): Record<string, string> | undefined {
  return rendererPresets[id]?.[theme];
}
